apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ipmi-plugin-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ipmi-plugin-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-ipmi-plugin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ipmi-plugin-role
subjects:
- kind: ServiceAccount
  name: kube-ipmi-plugin-sa
  namespace: default

